# Generated by Django 3.2.10 on 2022-01-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20220117_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='total',
            field=models.CharField(default='1', max_length=2000),
            preserve_default=False,
        ),
    ]
